end of day, yeesh, still have file upload issue

diff --git a/bin/redo b/bin/redo
--- a/bin/redo
+++ b/bin/redo
@@ -9,3 +9,16 @@ done
 sleep 2
 
 vagrant up
+
+sleep 10
+
+exit 1
+
+source ansiblerc
+
+if ! ans -a "ping -c 1 news.google.com"; then
+	echo "Pings failed..."
+	exit 1
+fi
+
+pb site.yml
